#!/bin/bash

# If not already installed, install Homebrew
if ! command -v brew &>/dev/null; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install packages listed in the Brewfile
if [[ -f ~/dotfiles/Brewfile ]]; then
  echo "Installing packages from Brewfile..."
  brew bundle --file=~/dotfiles/Brewfile
  brew upgrade
else
  echo "Brewfile not found in ~/dotfiles."
  exit 1
fi

# Install Oh My Zsh if not already installed
if [[ ! -d ~/.oh-my-zsh ]]; then
  echo "Installing Oh My Zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
# After installing oh-my-zsh, it backs up my .zshrc file to .zshrc.pre-oh-my-zsh and replaces it with
# a template file. Obviously I don't want this so I need to remove it and rename the backup file.
if [[ -f ~/.zshrc.pre-oh-my-zsh ]]; then
  echo "Removing stupid .zshrc template file generated by oh-my-zsh - using my .zshrc instead..."
  rm ~/.zshrc
  mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
fi
# Oh-my-zsh brings up a new shell here with the applied config, to continue the script, simply run 
# "exit"

# Install zsh-autosuggestions plugin if not already installed
if [[ ! -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ]]; then
  echo "Installing zsh-autosuggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
fi
# Oh-my-zsh brings up a new shell here with the applied config, to continue the script, simply run 
# "exit"
